load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "klog_library",
    srcs = glob(["*.kt"]),
    deps = [],
    visibility = ["//src/main/kotlin/com/clouway/common/logging:__pkg__"],
)
